In [24]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(A)
    augmented_matrix = np.hstack((A, b.reshape(-1,1)))  # Create [A | B]
    print("augmented_matrix:\n", augmented_matrix)
    # print("augmented_matrix[0:, 2]:\n", augmented_matrix[0:, 1])
    # print("abs(augmented_matrix[0:, 2]):\n",  abs(augmented_matrix[0:, 2]))
    # print("np.argmax(abs(augmented_matrix[0:, 2]):\n", np.argmax(abs(augmented_matrix[0:, 2])))
     
    for i in range(n):
       
        # Partial Pivoting: Swap rows to place largest element in current column at the diagonal
        max_row = np.argmax(abs(augmented_matrix[i:, i])) + i
        print("max_row1:", augmented_matrix[[max_row, i]])
        print("max_row2:", augmented_matrix[[max_row, i]])
        augmented_matrix[[i, max_row]] = augmented_matrix[[max_row, i]]
        
        # Make the pivot element 1
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]

        # Eliminate below the pivot
        for j in range(i + 1, n):
            augmented_matrix[j] -= augmented_matrix[j, i] * augmented_matrix[i]

    # Back-substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i+1:n], x[i+1:n])
    
    return x

# Example Usage
A = np.array([[3, 2, 1], [1, 0.5, -1], [1, 3/4, 1]], dtype=float)
b = np.array([7, 4, 5], dtype=float)

solution = gaussian_elimination(A, b)
print("Solution:", solution)


augmented_matrix:
 [[ 3.    2.    1.    7.  ]
 [ 1.    0.5  -1.    4.  ]
 [ 1.    0.75  1.    5.  ]]
max_row1: [[3. 2. 1. 7.]
 [3. 2. 1. 7.]]
max_row2: [[3. 2. 1. 7.]
 [3. 2. 1. 7.]]
max_row1: [[ 0.         -0.16666667 -1.33333333  1.66666667]
 [ 0.         -0.16666667 -1.33333333  1.66666667]]
max_row2: [[ 0.         -0.16666667 -1.33333333  1.66666667]
 [ 0.         -0.16666667 -1.33333333  1.66666667]]
max_row1: [[ 0.00000000e+00  0.00000000e+00 -3.33066907e-16  3.50000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.33066907e-16  3.50000000e+00]]
max_row2: [[ 0.00000000e+00  0.00000000e+00 -3.33066907e-16  3.50000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.33066907e-16  3.50000000e+00]]
Solution: [-5.25419957e+16  8.40671930e+16 -1.05083991e+16]
