In [ ]:
import numpy as numpy
import pandas as pd

In [1]:
import math

# Define the original vertices of the unit square
vertices = [(0, 0), (1, 0), (1, 1), (0, 1)]

# Define the translation vector (-1, 2)
translation_vector = (-1, 2)

# Step 1: Translate the vertices
translated_vertices = [(x + translation_vector[0], y + translation_vector[1]) for (x, y) in vertices]

# Define the rotation angle (50 degrees)
angle_deg = 50
angle_rad = math.radians(angle_deg)

# Step 2: Rotate the translated vertices
def rotate(x, y, angle):
    x_new = x * math.cos(angle) - y * math.sin(angle)
    y_new = x * math.sin(angle) + y * math.cos(angle)
    return (x_new, y_new)

# Apply rotation to each translated vertex
rotated_vertices = [rotate(x, y, angle_rad) for (x, y) in translated_vertices]

# Print the results
print("Original vertices of the unit square:")
print(vertices)

print("\nTranslated vertices (by (-1, 2)):")
print(translated_vertices)

print("\nRotated vertices (after 50 degrees rotation):")
for vertex in rotated_vertices:
    print(f"{vertex}")


Original vertices of the unit square:
[(0, 0), (1, 0), (1, 1), (0, 1)]

Translated vertices (by (-1, 2)):
[(-1, 2), (0, 2), (0, 3), (-1, 3)]

Rotated vertices (after 50 degrees rotation):
(-2.1748764959244955, 0.5195307762541007)
(-1.532088886237956, 1.2855752193730787)
(-2.298133329356934, 1.9283628290596182)
(-2.9409209390434734, 1.1623183859406403)


In [35]:
import numpy as np

A = np.array([[6, -1 ,1],
              [0, 2,3],
              [0, 2,3]
              ])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [6. 0. 5.]
Eigenvectors:
 [[ 1.00000000e+00 -2.25188675e-01  5.44331622e-17]
 [ 0.00000000e+00 -8.10679228e-01 -7.07106781e-01]
 [ 0.00000000e+00  5.40452819e-01 -7.07106781e-01]]


In [21]:
import numpy as np
import math

# Function to find the angle between two vectors
def angle_between_vectors(a, b):
    # Calculate dot product of a and b
    dot_product = np.dot(a, b)
    
    # Calculate the magnitudes (norms) of a and b
    magnitude_a = np.linalg.norm(a)
    magnitude_b = np.linalg.norm(b)
    
    # Calculate the cosine of the angle
    cos_theta = dot_product / (magnitude_a * magnitude_b)
    
    # Calculate the angle in radians
    angle_radians = np.arccos(cos_theta)
    
    # Convert the angle to degrees
    angle_degrees = math.degrees(angle_radians)
    
    return angle_degrees

# Example vectors a and b
a = np.array([1, 2, -2])
b = np.array([4, 0, -3])

# Calculate the angle between a and b
angle = angle_between_vectors(a, b)

print(f"The angle between the vectors is: {angle} degrees")


The angle between the vectors is: 48.18968510422141 degrees


In [22]:
import math

# Angle in degrees
angle_degrees = 48.18968510422141

# Convert the angle to radians
angle_radians = math.radians(angle_degrees)

# Calculate the cosine of the angle
cos_value = math.cos(angle_radians)

print(f"The cosine inverse value (cosine of the angle) is: {cos_value}")


The cosine inverse value (cosine of the angle) is: 0.6666666666666665


In [4]:
import numpy as np

# Function to compute determinant
def compute_determinant(matrix):
    return np.linalg.det(matrix)

# 2×2 Matrix
matrix_2x2 = np.array([[6, -1],
                        [0, 2]])

# 3×3 Matrix
matrix_3x3 = np.array([[6, -1, 1],
                        [0, 2, 3],
                        [0, 2, 3]])

# n×n Random Matrix
n = 4  # Change this for different sizes
matrix_nxn = np.random.randint(1, 10, (n, n))

# Compute determinants
det_2x2 = compute_determinant(matrix_2x2)
det_3x3 = compute_determinant(matrix_3x3)
det_nxn = compute_determinant(matrix_nxn)

# Print results
print("Determinant of 2×2 Matrix:", round(det_2x2, 2))
print("Determinant of 3×3 Matrix:", round(det_3x3, 2))
print(f"Determinant of {n}×{n} Matrix:", round(det_nxn, 2))


Determinant of 2×2 Matrix: 12.0
Determinant of 3×3 Matrix: 0.0
Determinant of 4×4 Matrix: 855.0


In [6]:
#adjust and inverse

import numpy as np

def matrix_cofactor(matrix):
    """Compute the cofactor matrix."""
    size = matrix.shape[0]
    cofactor_matrix = np.zeros((size, size))
    
    for i in range(size):
        for j in range(size):
            # Create the minor matrix by removing row i and column j
            minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            # Compute determinant of the minor matrix
            cofactor_matrix[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    
    return cofactor_matrix

def adjoint(matrix):
    """Compute the adjoint (adjugate) of a matrix."""
    cofactor_mat = matrix_cofactor(matrix)
    return cofactor_mat.T  # Transpose of cofactor matrix

def inverse(matrix):
    """Compute the inverse using adjoint method."""
    det = np.linalg.det(matrix)
    if det == 0:
        raise ValueError("Matrix is singular, inverse does not exist.")
    
    adj = adjoint(matrix)
    return adj / det  # A⁻¹ = (Adj(A)) / det(A)

# Define a 3x3 matrix
A = np.array([[2, 3, 1],
              [4, 5, 6],
              [7, 8, 9]])

# Compute adjoint and inverse
adj_A = adjoint(A)
try:
    inv_A = inverse(A)
except ValueError as e:
    inv_A = str(e)

print("Original Matrix:\n", A)
print("\nAdjoint (Adjugate) Matrix:\n", adj_A)
print("\nInverse Matrix:\n", inv_A)


Original Matrix:
 [[2 3 1]
 [4 5 6]
 [7 8 9]]

Adjoint (Adjugate) Matrix:
 [[ -3. -19.  13.]
 [  6.  11.  -8.]
 [ -3.   5.  -2.]]

Inverse Matrix:
 [[-0.33333333 -2.11111111  1.44444444]
 [ 0.66666667  1.22222222 -0.88888889]
 [-0.33333333  0.55555556 -0.22222222]]


In [8]:
#consistancy

import numpy as np

# Coefficient Matrix (A)
A = np.array([[2, 6, 0], 
              [6, 20, -6], 
              [0, 6, -18]])

# Augmented Matrix (A|B)
B = np.array([[-11], 
              [-3], 
              [-1]])

# Compute the ranks
rank_A = np.linalg.matrix_rank(A)
rank_A_B = np.linalg.matrix_rank(np.hstack((A, B)))

# Number of variables (columns in A)
num_variables = A.shape[1]

# Check consistency
if rank_A == rank_A_B:
    if rank_A == num_variables:
        print("The system is Consistent with a Unique Solution.")
    else:
        print("The system is Consistent with Infinitely Many Solutions.")
else:
    print("The system is Inconsistent (No Solution).")


The system is Inconsistent (No Solution).


In [9]:
#find the solution
from sympy import symbols, Eq, solve

# Define the variable b
b = symbols('b')

# Define the equation b^3 - 4b = 0
equation = Eq(b * (b**2 - 4), 0)

# Solve the equation
solutions = solve(equation, b)

# Display the solutions
print("The values of b that make the vectors orthogonal are:", solutions)


The values of b that make the vectors orthogonal are: [-2, 0, 2]


In [11]:
import numpy as np

def find_intersection_and_angle():
    # Define the vectors for line L and M (excluding parameters A and u)
    rL = np.array([0, -3, 3])  # Starting point of L
    dirL = np.array([3, -2, 1])  # Direction vector of L

    rM = np.array([7, -2, 4])  # Starting point of M
    dirM = np.array([-2, 1, -1])  # Direction vector of M

    # Create the system of equations from L = M
    # We want to solve: rL + A * dirL = rM + u * dirM
    # This simplifies to: (3, -2, 1) * A - (-2, 1, -1) * u = (7, -2, 4) - (0, -3, 3)

    coeff = np.array([[3, -2], [-2, 1], [1, -1]])  # Coefficient matrix for A and u
    rhs = np.array([7 - 0, -2 - (-3), 4 - 3])  # Right-hand side: (7, -2, 4) - (0, -3, 3)

    # Solve the linear system for A and u
    try:
        params = np.linalg.lstsq(coeff, rhs, rcond=None)[0]

        # Extract the values for A and u
        A_solution, u_solution = params[0], params[1]

        # Find the point of intersection by substituting A into L's equation
        intersection_point = rL + A_solution * dirL

        # Calculate the acute angle between L and M
        dot_product = np.dot(dirL, dirM)
        magnitude_L = np.linalg.norm(dirL)
        magnitude_M = np.linalg.norm(dirM)

        cos_theta = dot_product / (magnitude_L * magnitude_M)
        angle = np.arccos(np.clip(cos_theta, -1.0, 1.0))  # Ensure the value is within the valid range

        return intersection_point, np.degrees(angle), A_solution, u_solution
    except np.linalg.LinAlgError:
        return "The system has no solution."

# Call the function and display the results
intersection, angle, A_solution, u_solution = find_intersection_and_angle()

print("Point of intersection:", intersection)
print(f"Acute angle between lines (in degrees): {angle:.2f}")
print(f"Value of A: {A_solution}")
print(f"Value of u: {u_solution}")



Point of intersection: [-6.  1.  1.]
Acute angle between lines (in degrees): 169.11
Value of A: -2.000000000000003
Value of u: -5.333333333333336


In [12]:
#eigen values


import numpy as np

# Define the 3x3 matrix
A = np.array([[4, -2, 1],
              [1, 1, 0],
              [2, 3, 3]])

# Find the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display the results
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: \n", eigenvectors)


Eigenvalues:  [4.92585155+0.j         1.53707422+1.22253995j 1.53707422-1.22253995j]
Eigenvectors: 
 [[-0.56568946+0.j         -0.44382311+0.03548398j -0.44382311-0.03548398j]
 [-0.14409344+0.j         -0.1093548 +0.31499295j -0.1093548 -0.31499295j]
 [-0.81193135+0.j          0.83101318+0.j          0.83101318-0.j        ]]


In [16]:
import numpy as np

# Define vectors a and b
a = np.array([1, 1, 1])
b = np.array([1, -1, 1])

# Calculate the dot product of a and b
dot_product_ab = np.dot( b ,a)
print("Dot Product of a and b:", dot_product_ab)

# Calculate the dot product of a with itself (a · a)
dot_product_aa = np.dot(a, a)
print("Dot Product of a with itself:", dot_product_aa)

# Calculate the projection of b onto a
projection = (dot_product_ab / dot_product_aa) * a

print("Projection of b onto a:", projection)


Dot Product of a and b: 1
Dot Product of a with itself: 3
Projection of b onto a: [0.33333333 0.33333333 0.33333333]


In [20]:
print(1/math.sqrt(2))

0.7071067811865475


In [18]:
import math

In [26]:
import numpy as np

# Define the matrix
A = np.array([[1, 5, 0],
              [0, 0, 3],
              [0, 7, 4]], dtype=float)

# First set of row operations:
A1 = A.copy()

# R2 <-> R3
A1[[1, 2]] = A1[[2, 1]]
print("After R2 <-> R3:")
# print(A1)

# R2 -> R2 (No-op, so no change)
print("\nAfter R2 -> R2:")
# print(A1)

# R1 -> R1 - 5R2
A1[0] = A1[0] - 5 * A1[1]
print("\nAfter R1 -> R1 - 5R2:")
# print(A1)

# R3 -> 3R3
A1[2] = 3 * A1[2]
print("\nAfter R3 -> 3R3:")
# print(A1)

# R1 -> R1 + 29R3
A1[0] = A1[0] + 29 * A1[2]
print("\nAfter R1 -> R1 + 29R3:")
# print(A1)

# R2 -> R2 - 4R3
A1[1] = A1[1] - 4 * A1[2]
print("\nAfter R2 -> R2 - 4R3:")
print(A1)

print("second set===============================================")
# Second set of row operations:
A2 = A.copy()

# R2 <-> R3
A2[[1, 2]] = A2[[2, 1]]
print("\nSecond set: After R2 <-> R3:")
# print(A2)

# R2 -> 7R2
A2[1] = 7 * A2[1]
print("\nAfter R2 -> 7R2:")
# print(A2)

# R1 -> R1 - 5R2
A2[0] = A2[0] - 5 * A2[1]
print("\nAfter R1 -> R1 - 5R2:")
# print(A2)

# R2 -> 3R2
A2[1] = 3 * A2[1]
print("\nAfter R2 -> 3R2:")
# print(A2)

# R1 -> R1 + 29R3
A2[0] = A2[0] + 29 * A2[2]
print("\nAfter R1 -> R1 + 29R3:")
# print(A2)

# R2 -> R1 - 4R3
A2[1] = A2[0] - 4 * A2[2]
print("\nAfter R2 -> R1 - 4R3:")
print(A2)


After R2 <-> R3:

After R2 -> R2:

After R1 -> R1 - 5R2:

After R3 -> 3R3:

After R1 -> R1 + 29R3:

After R2 -> R2 - 4R3:
[[  1. -30. 241.]
 [  0.   7. -32.]
 [  0.   0.   9.]]
second set===============================================

Second set: After R2 <-> R3:

After R2 -> 7R2:

After R1 -> R1 - 5R2:

After R2 -> 3R2:

After R1 -> R1 + 29R3:

After R2 -> R1 - 4R3:
[[   1. -240.  -53.]
 [   1. -240.  -65.]
 [   0.    0.    3.]]


In [27]:
import numpy as np

# Define the 3x3 matrix
A = np.array([[1, 5, 0],
              [0, 0, 3],
              [0, 7, 4]])

# Check if the matrix is invertible by calculating the determinant
determinant = np.linalg.det(A)

if determinant != 0:
    # Find the inverse of the matrix
    inverse_matrix = np.linalg.inv(A)
    print("Inverse of the matrix A is:")
    print(inverse_matrix)
else:
    print("The matrix is not invertible (determinant is 0).")


Inverse of the matrix A is:
[[ 1.          0.95238095 -0.71428571]
 [ 0.         -0.19047619  0.14285714]
 [ 0.          0.33333333  0.        ]]


In [28]:
import numpy as np

# Define the matrix
A = np.array([[1, 5, 0],
              [0, 0, 3],
              [0, 7, 4]], dtype=float)

# Set 1 of operations:
A1 = A.copy()

# R2 <-> R3
A1[[1, 2]] = A1[[2, 1]]
print("Set 1: After R2 <-> R3:")
 

# R2 -> (1/7) * R2
A1[1] = (1/7) * A1[1]
print("\nSet 1: After R2 -> (1/7) * R2:")
 

# R1 -> R1 - 5 * R2
A1[0] = A1[0] - 5 * A1[1]
print("\nSet 1: After R1 -> R1 - 5 * R2:")
 

# R3 -> (1/3) * R3
A1[2] = (1/3) * A1[2]
print("\nSet 1: After R3 -> (1/3) * R3:")
 

# R1 -> R1 + (20/7) * R3
A1[0] = A1[0] + (20/7) * A1[2]
print("\nSet 1: After R1 -> R1 + (20/7) * R3:")
 

# R2 -> R2 - (4/7) * R3
A1[1] = A1[1] - (4/7) * A1[2]
print("\nSet 1: After R2 -> R2 - (4/7) * R3:")
print(A1)


# Set 2 of operations:
A2 = A.copy()

# R2 <-> R3
A2[[1, 2]] = A2[[2, 1]]
print("\nSet 2: After R2 <-> R3:")
 

# R2 -> (1/7) * R2
A2[1] = (1/7) * A2[1]
print("\nSet 2: After R2 -> (1/7) * R2:")
 
# R1 -> R1 - 5 * R2
A2[0] = A2[0] - 5 * A2[1]
print("\nSet 2: After R1 -> R1 - 5 * R2:")
 

# R2 -> (1/3) * R2
A2[1] = (1/3) * A2[1]
print("\nSet 2: After R2 -> (1/3) * R2:")
 

# R1 -> R1 + (20/7) * R3
A2[0] = A2[0] + (20/7) * A2[2]
print("\nSet 2: After R1 -> R1 + (20/7) * R3:")
 

# R2 -> R2 - (4/7) * R3
A2[1] = A2[1] - (4/7) * A2[2]
print("\nSet 2: After R2 -> R2 - (4/7) * R3:")
print(A2)


Set 1: After R2 <-> R3:

Set 1: After R2 -> (1/7) * R2:

Set 1: After R1 -> R1 - 5 * R2:

Set 1: After R3 -> (1/3) * R3:

Set 1: After R1 -> R1 + (20/7) * R3:

Set 1: After R2 -> R2 - (4/7) * R3:
[[1.0000000e+00 0.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]

Set 2: After R2 <-> R3:

Set 2: After R2 -> (1/7) * R2:

Set 2: After R1 -> R1 - 5 * R2:

Set 2: After R2 -> (1/3) * R2:

Set 2: After R1 -> R1 + (20/7) * R3:

Set 2: After R2 -> R2 - (4/7) * R3:
[[ 1.          0.          5.71428571]
 [ 0.          0.33333333 -1.52380952]
 [ 0.          0.          3.        ]]


In [29]:
import numpy as np

# Define the matrix
A = np.array([[1, 5, 0],
              [0, 0, 3],
              [0, 7, 4]], dtype=float)

# Set 1 of operations:
A1 = A.copy()

# R2 <-> R3
A1[[1, 2]] = A1[[2, 1]]
# R2 -> (1/7) * R1
A1[1] = (1/7) * A1[0]
# R1 -> R1 - 4 * R2
A1[0] = A1[0] - 4 * A1[1]
# R3 -> (1/3) * R3
A1[2] = (1/3) * A1[2]
# R1 -> R2 + (20/7) * R3
A1[0] = A1[1] + (20/7) * A1[2]
# R2 -> R2 - (4/7) * R3
A1[1] = A1[1] - (4/7) * A1[2]

print("Set 1 result:")
print(A1)

# Set 2 of operations:
A2 = A.copy()

# R2 <-> R3
A2[[1, 2]] = A2[[2, 1]]
# R2 -> (1/7) * R2
A2[1] = (1/7) * A2[1]
# R1 -> R1 - 5 * R2
A2[0] = A2[0] - 5 * A2[1]
# R3 -> (1/3) * R3
A2[2] = (1/3) * A2[2]
# R1 -> R1 + (20/7) * R3
A2[0] = A2[0] + (20/7) * A2[2]
# R2 -> R2 + (4/7) * R3
A2[1] = A2[1] + (4/7) * A2[2]

print("\nSet 2 result:")
print(A2)

# Set 3 of operations:
A3 = A.copy()

# R2 <-> R3
A3[[1, 2]] = A3[[2, 1]]
# R1 -> (1/7) * R1
A3[0] = (1/7) * A3[0]
# R1 -> R1 - 4 * R1
A3[0] = A3[0] - 4 * A3[0]
# R3 -> (1/5) * R3
A3[2] = (1/5) * A3[2]
# R1 -> R1 + (20/7) * R3
A3[0] = A3[0] + (20/7) * A3[2]
# R2 -> R2 - (3/7) * R3
A3[1] = A3[1] - (3/7) * A3[2]

print("\nSet 3 result:")
print(A3)


Set 1 result:
[[ 0.14285714  0.71428571  2.85714286]
 [ 0.14285714  0.71428571 -0.57142857]
 [ 0.          0.          1.        ]]

Set 2 result:
[[1.00000000e+00 0.00000000e+00 4.44089210e-16]
 [0.00000000e+00 1.00000000e+00 1.14285714e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Set 3 result:
[[-0.42857143 -2.14285714  1.71428571]
 [ 0.          7.          3.74285714]
 [ 0.          0.          0.6       ]]


In [30]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 0], [5, 3]])
B = np.array([[3, 2], [-1, 4]])

# Step 1: Calculate AB
AB = np.dot(A, B)

# Step 2: Calculate the inverse of AB
try:
    AB_inv = np.linalg.inv(AB)
    print("Inverse of AB:")
    print(AB_inv)
except np.linalg.LinAlgError:
    print("Matrix AB is singular, and its inverse does not exist.")


Inverse of AB:
[[ 0.52380952 -0.04761905]
 [-0.28571429  0.07142857]]


In [34]:
import numpy as np

# Define two 3x1 vectors
vector1 = np.array([1, 2, 3])  # Example vector 1
vector2 = np.array([4, -5, 6])  # Example vector 2

# Compute the dot product of the two vectors
dot_product = np.dot(vector1, vector2)

# Check if the dot product is zero
if dot_product == 0:
    print("The vectors are orthogonal.")
else:
    print("The vectors are not orthogonal.")


The vectors are not orthogonal.
