In [1]:
import numpy as numpy
import pandas as pd

In [2]:
u=pd.array([1 ,0.5 ,-1.25])
print(u)

v=2*u
w=3*u

print(v)
print(w)

<FloatingArray>
[1.0, 0.5, -1.25]
Length: 3, dtype: Float64
<FloatingArray>
[2.0, 1.0, -2.5]
Length: 3, dtype: Float64
<FloatingArray>
[3.0, 1.5, -3.75]
Length: 3, dtype: Float64


In [3]:
u=pd.array([2 ,-1,2])
v=pd.array([5 ,0,2])
x=pd.array([-7 ,1,2])
y=pd.array([0 ,8,3])


# a) (u+ v) ·(x+ y)
# b) ((3u·x)v) ·y
# c) u·x−4v·y
# d) u·x+ 3u·y−v·y
# e) (2(v+ u) ·u) −5u·y
# f) 4u·x+ 6 [v·(3x−y)]



a=numpy.dot(u+v,x+y)
b=numpy.dot(numpy.dot(3*u,x),v)
c=numpy.dot(u,x)-4*numpy.dot(v,y)
d=numpy.dot(u,x)+3*numpy.dot(u,y)-numpy.dot(v,y)
e=numpy.dot(2*(v+u),u)-5*numpy.dot(u,y)
f=4*numpy.dot(u,x)+6*(numpy.dot(v,3*x-y))

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)




-38
[-165    0  -66]
-35
-23
56
-638


In [4]:
# 2 Calculate ∥u∥ for each of the following vectors.

a=pd.array([-3 ,5])
b=pd.array([1,0,7])
c=pd.array([2,2,2,2])
d=pd.array([1,-1,2,-2,3])
e=pd.array([1,2,3,4,5,6])

norm_a=numpy.linalg.norm(a)
norm_b=numpy.linalg.norm(b)
norm_c=numpy.linalg.norm(c)
norm_d=numpy.linalg.norm(d)
norm_e=numpy.linalg.norm(e)


print(norm_a)
print(norm_b)
print(norm_c)
print(norm_d)
print(norm_e)


5.830951894845301
7.0710678118654755
4.0
4.358898943540674
9.539392014169456


In [5]:
# 4 For each pair of vectors u, v, calculate the angle between uand v
u1=pd.array([3 ,4])
v1=pd.array([5,12])

u2=pd.array([ 4 , 6])
v2=pd.array([-3 , 2])

u3=pd.array([ 2 ,2 ,-1])
v3=pd.array([5,-4,2])


def angle_between_vectors(v, u):
    dot_product = numpy.dot(v, u)  # Dot product
    norm_v = numpy.linalg.norm(v)  # Magnitude of v
    norm_u = numpy.linalg.norm(u)  # Magnitude of u
    cos_theta = dot_product / (norm_v * norm_u)  # Cosine of the angle
    angle = numpy.arccos(numpy.clip(cos_theta, -1.0, 1.0))  # Angle in radians
    return numpy.degrees(angle)  # Convert to degrees

print(angle_between_vectors(u1,v1))
print(angle_between_vectors(u2,v2))
print(angle_between_vectors(u3,v3))



14.250032697803595
90.0
90.0


In [6]:
#8 Find the orthogonal projection of the vector

u=pd.array([1 ,-2,1])
v=pd.array([4 , -4 ,7])

# projection of V on U
def projection(v, u):
    dot_product = numpy.dot( u , v)  # Dot product
    norm_u_squared = numpy.dot(u, u)  # Magnitude squared of u
    proj = (dot_product / norm_u_squared) * u  # Projection formula
    return proj

print(projection(u,v))
 

<FloatingArray>
[0.9382716049382716, -0.9382716049382716, 1.6419753086419753]
Length: 3, dtype: Float64


In [7]:
# find the roots

import numpy as np

# Coefficients of the cubic equation a^3 + 2a - 36 = 0
coefficients = [1, 0, 2, -36]

# Find the roots using numpy's roots function
roots = np.roots(coefficients)
print(roots)


[-1.55014595+3.03460992j -1.55014595-3.03460992j  3.1002919 +0.j        ]


In [10]:

#unit vector in u
u=numpy.array([2,-3,1])
print(u / numpy.linalg.norm(u))

#unit vector in v
v=numpy.array([7 , -5, 1])

#Find a unit vector perpendicular to both uand v
import numpy

def unit_vector_orthogonal_to_vectors(u, v):
    unit_vector = numpy.cross(u, v)  # Cross product
    unit_vector = unit_vector / numpy.linalg.norm(unit_vector)  # Normalize and cast to float
    return unit_vector
 

print(unit_vector_orthogonal_to_vectors(u, v))

[ 0.53452248 -0.80178373  0.26726124]
[0.16329932 0.40824829 0.89814624]
